### ISSUE TITLE
`changeFullName` user Mutation

### ISSUE THREAD

**Issue by d-e-v-esh** [codeisscience/journal-policy-tracker-backend#72]
Currently there is no way for a registered user to change its `fullName`. Create a `changeFullName` mutation which will let users change their current `fullName`.

**Comment by hazardemircan** [comment]
Hey can i take this issue, i recently started to GraphQL :)

**Comment by d-e-v-esh** [comment]
For sure, I'll assign it to you. Let me know if you have any problems. I'll be happy to help 👍

**Comment by d-e-v-esh** [comment]
@hazardemircan For sure, I'll assign it to you. Let me know if you have any problems. I'll be happy to help 👍

**Comment by hazardemircan** [comment]
@d-e-v-esh I created the mutation but i put LoginInput as a parameter so the user have to login to change userName. Because i couldn't get currentUser from the session, this could be bug. 

Should i PR with this way or do you want me to fix it.

` changeFullName: async (_, { userInfo }) => {
      const { usernameOrEmail, password } = userInfo.loginInfo;
      const { newUsername } = userInfo;

      let user;
      if (!validator.isEmail(usernameOrEmail)) {
        user = await User.findOne({ username: usernameOrEmail });
      } else {
        user = await User.findOne({ email: usernameOrEmail });
      }

      if (!user) {
        return {
          errors: [
            {
              field: "usernameOrEmail",
              message: "that username or email does not exist",
            },
          ],
        };
      }

      const isPasswordValid = await bcrypt.compare(password, user.password);

      if (isPasswordValid) {
        if (user.username !== newUsername) {
          await user.updateOne({
            username: newUsername,
            updatedAt: new Date(),
          });
        } else {
          return {
            errors: [
              {
                field: "newUsername",
                message:
                  "new username cannot be the same as the previous username",
              },
            ],
          };
        }
      } else {
        return {
          errors: [
            {
              field: "password",
              message: "incorrect password",
            },
          ],
        };
      }

      return { user };
    },
  },
};`

**Comment by hazardemircan** [comment]
@d-e-v-esh I created the mutation but seems like auth is not working.

req.session.userId is setting in login mutation but there is no userid field in req.session that is why isAuth function is not working.
I put a login control in changeFullname mutation since session is not working.

I would love to fix this issue too, thanks.
Please tell me if i understood wrong or misspell annything.

**Comment by hazardemircan** [comment]
@d-e-v-esh I sent PR  on #77 , can you review it. If i have to write tests let me know. 

thanks...

**Comment by d-e-v-esh** [comment]
I'll take a look at it and see what it problem is. Give me some time. 👍

**Comment by hazardemircan** [comment]
Hi @d-e-v-esh  sorry for delay, i was very busy. i would like to complete this issue.

**Comment by d-e-v-esh** [comment]
@hazardemircan Yes, make a PR when you are done 👍
